export const samplePlaces = [
  { place_id: "1", description: "New York, USA" },
  { place_id: "2", description: "Los Angeles, USA" },
  { place_id: "3", description: "Chicago, USA" },
  { place_id: "4", description: "Houston, USA" },
  { place_id: "5", description: "Phoenix, USA" },
  { place_id: "6", description: "Philadelphia, USA" },
  { place_id: "7", description: "San Antonio, USA" },
  { place_id: "8", description: "San Diego, USA" },
  { place_id: "9", description: "Dallas, USA" },
  { place_id: "10", description: "San Jose, USA" },
  { place_id: "11", description: "Austin, USA" },
  { place_id: "12", description: "Jacksonville, USA" },
  { place_id: "13", description: "Fort Worth, USA" },
  { place_id: "14", description: "Columbus, USA" },
  { place_id: "15", description: "Charlotte, USA" },
  { place_id: "16", description: "San Francisco, USA" },
  { place_id: "17", description: "Indianapolis, USA" },
  { place_id: "18", description: "Seattle, USA" },
  { place_id: "19", description: "Denver, USA" },
  { place_id: "20", description: "Washington, D.C., USA" },
  { place_id: "21", description: "Boston, USA" },
  { place_id: "22", description: "El Paso, USA" },
  { place_id: "23", description: "Nashville, USA" },
  { place_id: "24", description: "Detroit, USA" },
  { place_id: "25", description: "Oklahoma City, USA" },
  { place_id: "26", description: "Las Vegas, USA" },
  { place_id: "27", description: "Memphis, USA" },
  { place_id: "28", description: "Louisville, USA" },
  { place_id: "29", description: "Baltimore, USA" },
  { place_id: "30", description: "Milwaukee, USA" },
  { place_id: "31", description: "Albuquerque, USA" },
  { place_id: "32", description: "Tucson, USA" },
  { place_id: "33", description: "Fresno, USA" },
  { place_id: "34", description: "Sacramento, USA" },
  { place_id: "35", description: "Mesa, USA" },
  { place_id: "36", description: "Kansas City, USA" },
  { place_id: "37", description: "Atlanta, USA" },
  { place_id: "38", description: "Long Beach, USA" },
  { place_id: "39", description: "Omaha, USA" },
  { place_id: "40", description: "Raleigh, USA" },
  { place_id: "41", description: "Colorado Springs, USA" },
  { place_id: "42", description: "Miami, USA" },
  { place_id: "43", description: "Virginia Beach, USA" },
  { place_id: "44", description: "Oakland, USA" },
  { place_id: "45", description: "Minneapolis, USA" },
  { place_id: "46", description: "Tulsa, USA" },
  { place_id: "47", description: "Arlington, USA" },
  { place_id: "48", description: "New Orleans, USA" },
  { place_id: "49", description: "Wichita, USA" },
  { place_id: "50", description: "Cleveland, USA" },
  { place_id: "51", description: "Tampa, USA" },
  { place_id: "52", description: "Bakersfield, USA" },
  { place_id: "53", description: "Aurora, USA" },
  { place_id: "54", description: "Anaheim, USA" },
  { place_id: "55", description: "Honolulu, USA" },
  { place_id: "56", description: "Santa Ana, USA" },
  { place_id: "57", description: "Riverside, USA" },
  { place_id: "58", description: "Corpus Christi, USA" },
  { place_id: "59", description: "Lexington, USA" },
  { place_id: "60", description: "Henderson, USA" },
  { place_id: "61", description: "Stockton, USA" },
  { place_id: "62", description: "Saint Paul, USA" },
  { place_id: "63", description: "Cincinnati, USA" },
  { place_id: "64", description: "St. Louis, USA" },
  { place_id: "65", description: "Pittsburgh, USA" },
  { place_id: "66", description: "Greensboro, USA" },
  { place_id: "67", description: "Lincoln, USA" },
  { place_id: "68", description: "Anchorage, USA" },
  { place_id: "69", description: "Plano, USA" },
  { place_id: "70", description: "Orlando, USA" },
  { place_id: "71", description: "Irvine, USA" },
  { place_id: "72", description: "Newark, USA" },
  { place_id: "73", description: "Durham, USA" },
  { place_id: "74", description: "Chula Vista, USA" },
  { place_id: "75", description: "Toledo, USA" },
  { place_id: "76", description: "Fort Wayne, USA" },
  { place_id: "77", description: "St. Petersburg, USA" },
  { place_id: "78", description: "Laredo, USA" },
  { place_id: "79", description: "Jersey City, USA" },
  { place_id: "80", description: "Chandler, USA" },
  { place_id: "81", description: "Madison, USA" },
  { place_id: "82", description: "Lubbock, USA" },
  { place_id: "83", description: "Scottsdale, USA" },
  { place_id: "84", description: "Reno, USA" },
  { place_id: "85", description: "Buffalo, USA" },
  { place_id: "86", description: "Gilbert, USA" },
  { place_id: "87", description: "Glendale, USA" },
  { place_id: "88", description: "North Las Vegas, USA" },
  { place_id: "89", description: "Winston-Salem, USA" },
  { place_id: "90", description: "Chesapeake, USA" },
  { place_id: "91", description: "Norfolk, USA" },
  { place_id: "92", description: "Fremont, USA" },
  { place_id: "93", description: "Garland, USA" },
  { place_id: "94", description: "Irving, USA" },
  { place_id: "95", description: "Hialeah, USA" },
  { place_id: "96", description: "Richmond, USA" },
  { place_id: "97", description: "Boise, USA" },
  { place_id: "98", description: "Spokane, USA" },
  { place_id: "99", description: "Baton Rouge, USA" },
  { place_id: "100", description: "Tacoma, USA" },
];
